# Generated by Django 3.1.7 on 2021-05-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('domains', models.TextField(verbose_name="Target's Domains")),
                ('overview', models.CharField(default='N/A', max_length=255, verbose_name='Overview')),
                ('actions', models.CharField(choices=[('LIST', 'List Up'), ('SCAN', 'Vulnerability assessment')], max_length=4, verbose_name='Action mode')),
            ],
        ),
    ]
