# Generated by Django 3.1.7 on 2021-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetdomain',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='targetdomain',
            name='domains',
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='domain',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='registration_date',
            field=models.CharField(default=False, max_length=255, verbose_name='Registration'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='subdomain',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='targetdomain',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Organization Name'),
        ),
    ]
