# Generated by Django 3.1.7 on 2021-05-05 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0002_auto_20210505_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdomain',
            name='status',
            field=models.CharField(default='N/A', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='targetdomain',
            name='domain',
            field=models.IntegerField(default=0, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='targetdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 7, 30, 38, 344249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='targetdomain',
            name='subdomain',
            field=models.IntegerField(default=0, verbose_name='Subdomain'),
        ),
    ]
