# Generated by Django 3.1.7 on 2021-05-06 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0003_auto_20210505_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('overview', models.CharField(default='N/A', max_length=255, verbose_name='Overview')),
                ('domain', models.IntegerField(default=0, verbose_name='Domain')),
                ('subdomain', models.IntegerField(default=0, verbose_name='Subdomain')),
                ('status', models.CharField(default='N/A', max_length=1, verbose_name='Status')),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 0, 55, 25, 453520, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='TargetDomain',
        ),
    ]
