# Generated by Django 3.1.7 on 2021-05-06 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0004_auto_20210506_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Domain Name')),
                ('registrar', models.CharField(default='N/A', max_length=255, verbose_name='Registrar')),
                ('administrative_contact', models.CharField(default='N/A', max_length=255, verbose_name='Administrative Contact')),
                ('registrant_name', models.CharField(default='N/A', max_length=255, verbose_name='Registrant Name')),
                ('registrant_organization', models.CharField(default='N/A', max_length=255, verbose_name='Registrant Organization')),
                ('registrant_email', models.CharField(default='N/A', max_length=255, verbose_name='Registrant Email')),
                ('admin_name', models.CharField(default='N/A', max_length=255, verbose_name='Admin Name')),
                ('admin_organization', models.CharField(default='N/A', max_length=255, verbose_name='Admin Organization')),
                ('admin_email', models.CharField(default='N/A', max_length=255, verbose_name='Admin Email')),
                ('tech_name', models.CharField(default='N/A', max_length=255, verbose_name='Tech Name')),
                ('tech_organization', models.CharField(default='N/A', max_length=255, verbose_name='Tech Organization')),
                ('tech_email', models.CharField(default='N/A', max_length=255, verbose_name='Tech Email')),
                ('name_server', models.CharField(default='N/A', max_length=1000, verbose_name='Name Server')),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 4, 58, 40, 765699, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_domain', models.CharField(max_length=255, verbose_name='Domain Name')),
                ('name', models.CharField(max_length=255, verbose_name='Subdomain Name')),
                ('ip_address', models.CharField(default='N/A', max_length=15, verbose_name='IP Address')),
                ('http_accessible', models.CharField(default='N/A', max_length=255, verbose_name='Accessible (HTTP)')),
                ('http_location', models.CharField(default='N/A', max_length=1000, verbose_name='Location (HTTP)')),
                ('http_page_title', models.CharField(default='N/A', max_length=1000, verbose_name='Page Title (HTTP)')),
                ('http_screenshot_url', models.CharField(default='N/A', max_length=1000, verbose_name='Screenshot Captured URL (HTTP)')),
                ('http_screenshot_path', models.CharField(default='N/A', max_length=1000, verbose_name='Path to save the Screenshot (HTTP)')),
                ('https_accessible', models.CharField(default='N/A', max_length=255, verbose_name='Accessible (HTTPS)')),
                ('https_location', models.CharField(default='N/A', max_length=1000, verbose_name='Location (HTTPS)')),
                ('https_page_title', models.CharField(default='N/A', max_length=1000, verbose_name='Page Title (HTTPS)')),
                ('https_screenshot_url', models.CharField(default='N/A', max_length=1000, verbose_name='Screenshot Captured URL (HTTPS)')),
                ('https_screenshot_path', models.CharField(default='N/A', max_length=1000, verbose_name='Path to save the Screenshot (HTTPS)')),
                ('dns_a_record', models.CharField(default='N/A', max_length=5000, verbose_name='DNS A Record')),
                ('dns_cname_record', models.CharField(default='N/A', max_length=5000, verbose_name='DNS CNAME Record')),
                ('dns_ns_record', models.CharField(default='N/A', max_length=5000, verbose_name='DNS NS Record')),
                ('dns_mx_record', models.CharField(default='N/A', max_length=5000, verbose_name='DNS MX Record')),
                ('dns_soa_record', models.CharField(default='N/A', max_length=5000, verbose_name='DNS SOA Record')),
                ('dns_txt_record', models.CharField(default='N/A', max_length=5000, verbose_name='DNS TXT Record')),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 4, 58, 40, 766259, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 4, 58, 40, 765144, tzinfo=utc)),
        ),
    ]
