# Generated by Django 3.1.7 on 2021-05-06 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0006_auto_20210506_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='organization_id',
            field=models.IntegerField(default=0, verbose_name='Organization ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 8, 22, 59, 708925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 8, 22, 59, 708437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 8, 22, 59, 709493, tzinfo=utc)),
        ),
    ]
