# Generated by Django 3.1.7 on 2021-05-07 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0007_auto_20210506_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='subdomain',
            field=models.IntegerField(default=0, verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 8, 25, 32, 207913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 8, 25, 32, 207397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 8, 25, 32, 208509, tzinfo=utc)),
        ),
    ]
