# Generated by Django 3.1.7 on 2021-05-10 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0008_auto_20210507_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 5, 1, 56, 656446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 5, 1, 56, 655918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 5, 1, 56, 657018, tzinfo=utc)),
        ),
    ]
