# Generated by Django 3.1.7 on 2021-05-10 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0009_auto_20210510_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='status',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 6, 35, 6, 724446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 6, 35, 6, 723931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 6, 35, 6, 725062, tzinfo=utc)),
        ),
    ]
