# Generated by Django 3.1.7 on 2021-05-10 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0011_auto_20210510_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='related_organization_id',
            field=models.IntegerField(default=0, verbose_name='Related Organization ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 6, 50, 14, 780669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 6, 50, 14, 780063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 6, 50, 14, 781293, tzinfo=utc)),
        ),
    ]
