# Generated by Django 3.1.7 on 2021-05-12 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0014_auto_20210511_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='rank',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='organization',
            name='rank',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='rank',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 2, 16, 59, 768327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 2, 16, 59, 767796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 2, 16, 59, 768943, tzinfo=utc)),
        ),
    ]
