# Generated by Django 3.1.7 on 2021-05-12 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0015_auto_20210512_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='invisible',
            field=models.BooleanField(default=False, verbose_name='Invisible'),
        ),
        migrations.AddField(
            model_name='organization',
            name='invisible',
            field=models.BooleanField(default=False, verbose_name='Invisible'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='invisible',
            field=models.BooleanField(default=False, verbose_name='Invisible'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 3, 15, 40, 140888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 3, 15, 40, 140349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 3, 15, 40, 141470, tzinfo=utc)),
        ),
    ]
