# Generated by Django 3.1.7 on 2021-05-12 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0017_auto_20210512_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 9, 4, 2, 407702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 9, 4, 2, 406463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Energy'), (2, 'Materials'), (3, 'Industrials'), (4, 'Consumer Discretionary'), (5, 'Consumer Staples'), (6, 'Health Care'), (7, 'Financials'), (8, 'Information Technology'), (9, 'Communication Services'), (10, 'Utilities'), (11, 'Real Estate')], default=0, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='overview',
            field=models.CharField(default='', max_length=255, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Domestic'), (2, 'Abroad')], default=0, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 9, 4, 2, 405837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 9, 4, 2, 407200, tzinfo=utc)),
        ),
    ]
