# Generated by Django 3.1.7 on 2021-05-12 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0022_auto_20210512_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 13, 8, 17, 398383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 13, 8, 17, 397083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 13, 8, 17, 396409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='dns_a_record',
            field=models.TextField(default='N/A', max_length=5000, verbose_name='DNS A Record'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='dns_cname_record',
            field=models.TextField(default='N/A', max_length=5000, verbose_name='DNS CNAME Record'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='dns_mx_record',
            field=models.TextField(default='N/A', max_length=5000, verbose_name='DNS MX Record'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='dns_ns_record',
            field=models.TextField(default='N/A', max_length=5000, verbose_name='DNS NS Record'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='dns_soa_record',
            field=models.TextField(default='N/A', max_length=5000, verbose_name='DNS SOA Record'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='dns_txt_record',
            field=models.TextField(default='N/A', max_length=5000, verbose_name='DNS TXT Record'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='production',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Development'), (2, 'Launched')], default=0, verbose_name='Production Environment'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 13, 8, 17, 397867, tzinfo=utc)),
        ),
    ]
