# Generated by Django 3.1.7 on 2021-05-12 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0023_auto_20210512_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 3, 18, 510296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 3, 18, 509051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Search'), (2, 'Assess')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 3, 18, 508413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Search'), (2, 'Assess')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 3, 18, 509801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='status',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Search'), (2, 'Assess')], default=0, verbose_name='Status'),
        ),
    ]
