# Generated by Django 3.1.7 on 2021-05-12 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0024_auto_20210513_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='overview',
            field=models.TextField(default='', max_length=1000, verbose_name='Overview'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='overview',
            field=models.TextField(default='', max_length=1000, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 24, 8, 543260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 24, 8, 541985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 24, 8, 541295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 20, 24, 8, 542784, tzinfo=utc)),
        ),
    ]
