# Generated by Django 3.1.7 on 2021-05-14 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0025_auto_20210513_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 9, 13, 34, 881706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 9, 13, 34, 880384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 9, 13, 34, 879731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip_address',
            field=models.TextField(default='N/A', max_length=255, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='production',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Development'), (2, 'Production')], default=0, verbose_name='Production Environment'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 9, 13, 34, 881163, tzinfo=utc)),
        ),
    ]
