# Generated by Django 3.1.7 on 2021-05-14 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0026_auto_20210514_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 11, 52, 41, 517839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 11, 52, 41, 516472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 11, 52, 41, 515728, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 11, 52, 41, 517245, tzinfo=utc)),
        ),
    ]
