# Generated by Django 3.1.7 on 2021-06-03 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gyoithon', '0028_auto_20210528_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scan_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 4, 38, 19, 232355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='overview',
            field=models.TextField(default='N/A', max_length=1000, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 4, 38, 19, 231022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='overview',
            field=models.TextField(default='N/A', max_length=1000, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 4, 38, 19, 230288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='overview',
            field=models.TextField(default='N/A', max_length=1000, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 4, 38, 19, 231762, tzinfo=utc)),
        ),
    ]
