# Generated by Django 3.1.7 on 2021-03-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Target name')),
                ('overview', models.CharField(max_length=255, verbose_name='Overview')),
                ('last_scan_date', models.DateTimeField(max_length=255, verbose_name='Last scan date')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_result', models.TextField(blank=True, verbose_name='スキャン結果')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_result', to='atd.target', verbose_name='スキャン結果')),
            ],
        ),
    ]
