# Generated by Django 3.1.7 on 2021-03-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='rank',
            field=models.CharField(default='S', max_length=1, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_scan_date',
            field=models.DateField(verbose_name='Last scan date'),
        ),
    ]
