# Generated by Django 3.1.7 on 2021-03-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0002_auto_20210324_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='model/', verbose_name='Target model upload')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Upload',
            },
        ),
    ]
