# Generated by Django 3.1.7 on 2021-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0007_auto_20210325_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSettingFGSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.IntegerField(default=0.05, verbose_name='Epsilon')),
                ('eps_step', models.IntegerField(default=0.1, verbose_name='Epsilon Step')),
                ('targeted', models.BooleanField(default=False, verbose_name='Targeted')),
                ('batch_size', models.IntegerField(default=32, verbose_name='Batch Size')),
            ],
        ),
    ]
