# Generated by Django 3.1.7 on 2021-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0009_auto_20210329_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='attack_method',
            field=models.CharField(default='', max_length=255),
        ),
    ]
