# Generated by Django 3.1.7 on 2021-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0011_auto_20210329_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtEvasionFGSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=36)),
                ('epsilon', models.FloatField()),
                ('eps_step', models.FloatField()),
                ('targeted', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('countermeasure', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'EvasionFGSMTBL',
            },
        ),
        migrations.CreateModel(
            name='ExtScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=36)),
                ('status', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1000)),
                ('target_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('x_train_path', models.CharField(max_length=255)),
                ('x_train_num', models.IntegerField()),
                ('y_train_path', models.CharField(max_length=255)),
                ('x_test_path', models.CharField(max_length=255)),
                ('x_test_num', models.IntegerField()),
                ('y_test_path', models.CharField(max_length=255)),
                ('operation_type', models.CharField(max_length=255)),
                ('attack_type', models.CharField(max_length=255)),
                ('attack_method', models.CharField(max_length=255)),
                ('defence_type', models.CharField(max_length=255)),
                ('defence_method', models.CharField(max_length=255)),
                ('exec_start_date', models.CharField(max_length=255)),
                ('exec_end_date', models.CharField(max_length=255)),
                ('report_path', models.CharField(max_length=255)),
                ('report_html', models.CharField(max_length=255)),
                ('report_ipynb', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ScanResultTBL',
            },
        ),
        migrations.CreateModel(
            name='ExtScanResultEvasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=36)),
                ('consequence', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1000)),
                ('attack_method', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
            ],
            options={
                'db_table': 'ScanResultEvasionTBL',
            },
        ),
    ]
