# Generated by Django 3.1.7 on 2021-04-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0012_extevasionfgsm_extscanresult_extscanresultevasion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extevasionfgsm',
            old_name='eps_step',
            new_name='epsilon_step',
        ),
    ]
