# Generated by Django 3.1.7 on 2021-04-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0013_auto_20210402_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansettingfgsm',
            name='eps',
            field=models.FloatField(default=0.05, verbose_name='Epsilon'),
        ),
        migrations.AlterField(
            model_name='scansettingfgsm',
            name='eps_step',
            field=models.FloatField(default=0.1, verbose_name='Epsilon Step'),
        ),
    ]
