# Generated by Django 3.1.7 on 2021-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0015_auto_20210403_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='registration_date',
            field=models.CharField(default=False, max_length=255, verbose_name='Registration'),
        ),
    ]
