# Generated by Django 3.1.7 on 2021-04-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0016_target_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extevasionfgsm',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
