# Generated by Django 3.1.7 on 2021-04-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0017_extevasionfgsm_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extevasionfgsm',
            name='id',
        ),
        migrations.AlterField(
            model_name='extevasionfgsm',
            name='target_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
