# Generated by Django 3.1.7 on 2021-04-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0018_auto_20210405_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extevasionfgsm',
            name='target_id',
        ),
        migrations.AddField(
            model_name='extevasionfgsm',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
