# Generated by Django 3.1.7 on 2021-04-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0019_auto_20210405_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extevasionfgsm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='extscanresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='extscanresultevasion',
            name='id',
        ),
        migrations.AddField(
            model_name='extevasionfgsm',
            name='target_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extscanresult',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extscanresultevasion',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extscanresult',
            name='scan_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extscanresultevasion',
            name='scan_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
