# Generated by Django 3.1.7 on 2021-04-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0020_auto_20210405_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtEvasionCnW',
            fields=[
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=36)),
                ('confidence', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('countermeasure', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'EvasionCnWTBL',
            },
        ),
        migrations.CreateModel(
            name='ExtEvasionJSMA',
            fields=[
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=36)),
                ('theta', models.FloatField()),
                ('gamma', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('countermeasure', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'EvasionJSMATBL',
            },
        ),
        migrations.CreateModel(
            name='ScanSettingCnW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confidence')),
                ('batch_size', models.IntegerField(default=1, verbose_name='Batch Size')),
            ],
        ),
        migrations.CreateModel(
            name='ScanSettingJSMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theta', models.FloatField(default=0.1, verbose_name='Theta')),
                ('gamma', models.FloatField(default=1.0, verbose_name='Gamma')),
                ('batch_size', models.IntegerField(default=1, verbose_name='Batch Size')),
            ],
        ),
    ]
