# Generated by Django 3.1.7 on 2021-04-06 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0021_extevasioncnw_extevasionjsma_scansettingcnw_scansettingjsma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_model',
            field=models.FileField(default=1, upload_to='atd/target/%Y%m%d%H%M%S%f', validators=[django.core.validators.FileExtensionValidator(['h5'])], verbose_name='Model File (*.h5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_x_test',
            field=models.FileField(default=1, upload_to='atd/target/%Y%m%d%H%M%S%f', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='X_test File (*.npz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_x_train',
            field=models.FileField(default=1, upload_to='atd/target/%Y%m%d%H%M%S%f', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='X_train File (*.npz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_y_test',
            field=models.FileField(default=1, upload_to='atd/target/%Y%m%d%H%M%S%f', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='y_test File (*.npz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_y_train',
            field=models.FileField(default=1, upload_to='atd/target/%Y%m%d%H%M%S%f', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='y_train File (*.npz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='x_test',
            field=models.CharField(default=1, max_length=255, verbose_name='X_test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='x_train',
            field=models.CharField(default=1, max_length=255, verbose_name='X_train'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='y_test',
            field=models.CharField(default=1, max_length=255, verbose_name='y_test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='y_train',
            field=models.CharField(default=1, max_length=255, verbose_name='y_train'),
            preserve_default=False,
        ),
    ]
