# Generated by Django 3.1.7 on 2021-04-07 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0022_auto_20210406_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansettingcnw',
            name='use_dataset_num',
            field=models.IntegerField(default=100, verbose_name="Using dataset's number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scansettingfgsm',
            name='use_dataset_num',
            field=models.IntegerField(default=100, verbose_name="Using dataset's number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scansettingjsma',
            name='use_dataset_num',
            field=models.IntegerField(default=100, verbose_name="Using dataset's number"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_model',
            field=models.FileField(upload_to='atd/target/DFfSNaC1aUTV78QnHmMJXsTHzeWGNqRsIPnXiJEBm6d5Zh95', validators=[django.core.validators.FileExtensionValidator(['h5'])], verbose_name='Model File (*.h5)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_x_test',
            field=models.FileField(upload_to='atd/target/DFfSNaC1aUTV78QnHmMJXsTHzeWGNqRsIPnXiJEBm6d5Zh95', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='X_test File (*.npz)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_x_train',
            field=models.FileField(upload_to='atd/target/DFfSNaC1aUTV78QnHmMJXsTHzeWGNqRsIPnXiJEBm6d5Zh95', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='X_train File (*.npz)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_y_test',
            field=models.FileField(upload_to='atd/target/DFfSNaC1aUTV78QnHmMJXsTHzeWGNqRsIPnXiJEBm6d5Zh95', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='y_test File (*.npz)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_y_train',
            field=models.FileField(upload_to='atd/target/DFfSNaC1aUTV78QnHmMJXsTHzeWGNqRsIPnXiJEBm6d5Zh95', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='y_train File (*.npz)'),
        ),
    ]
