# Generated by Django 3.1.7 on 2021-04-07 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atd', '0024_auto_20210407_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scansettingfgsm',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='scansettingfgsm',
            name='eps_step',
        ),
        migrations.AddField(
            model_name='scansettingfgsm',
            name='epsilon',
            field=models.FloatField(default=0.05, verbose_name='Epsilon'),
        ),
        migrations.AddField(
            model_name='scansettingfgsm',
            name='epsilon_step',
            field=models.FloatField(default=0.1, verbose_name='Epsilon Step'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_model',
            field=models.FileField(upload_to='atd/target/ab4OVWpAlYeEbli8hEmxp3JtmJnvraOoUytYVW5QfhOF4SfD', validators=[django.core.validators.FileExtensionValidator(['h5'])], verbose_name='Model File (*.h5)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_x_test',
            field=models.FileField(upload_to='atd/target/ab4OVWpAlYeEbli8hEmxp3JtmJnvraOoUytYVW5QfhOF4SfD', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='X_test File (*.npz)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_x_train',
            field=models.FileField(upload_to='atd/target/ab4OVWpAlYeEbli8hEmxp3JtmJnvraOoUytYVW5QfhOF4SfD', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='X_train File (*.npz)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_y_test',
            field=models.FileField(upload_to='atd/target/ab4OVWpAlYeEbli8hEmxp3JtmJnvraOoUytYVW5QfhOF4SfD', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='y_test File (*.npz)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_y_train',
            field=models.FileField(upload_to='atd/target/ab4OVWpAlYeEbli8hEmxp3JtmJnvraOoUytYVW5QfhOF4SfD', validators=[django.core.validators.FileExtensionValidator(['npz'])], verbose_name='y_train File (*.npz)'),
        ),
    ]
